package azias.game.dungeoncrawler.dataproxies;

/**
 * Contains basic informations about the loaded map.
 * @author Azias
 */
public class MapDatas
{
	public static String[][] mapTiles;
	public static String[][] mapEntities;
	public static String[][] mapNpcs;
	public static String[][] mapMonster;

	public static String[][] infoNpcs;
	public static String[][] infoMonster;

	public static int npcNumber;
	public static int monsterNumber;
	
	public static int mapSizeX;
	public static int mapSizeY;
	
	public static int mapTilesetID;
	public static boolean hasNpc;
	public static boolean hasMonster;
	
	public static String mapMercenaryCamp = "TTTTTTTTTTTPTTTTTTTTTTTTTTTTTT;TTTTTTTTTT_PTTTTTTTTTTTTTTTTTT;TTTTTTTTT_PPTTTTTTTTTTTTTTTTTT;TTTTTTT___P__TTTTTTTTTTTTTTTTT;TTTTT____PP_____TT__TTTTTTTTTT;TTWWWWWW_P____________TTTTTTTT;TTWFFFFW_P____WWWWW____TTTTTTT;TTWFFFFW_P____WFFFW_T_____TTTT;TTWFFFFDPPP__TWFFFW________TTT;TTWFFFFW__P__WWWDWWT_______TTT;TTWDWWWW__PP_WFFFFWT_______TTT;TTWFFFW____P_WFFFFW_______TTTT;TTWFFFW_T__P_WFFFFW_______TTTT;TTWWWWW____P_WFFFFW____T__TTTT;TTTT______PP_WWDWWW__BBBBBTTTT;PPP___PPPPP____P____BB___B_TTT;TTPPPPP___P___PP___TB____B_TTT;TTWWDWW___PP__P_____B____B__TT;TTWFFFWWWW_P_PP_________BB__TT;TTWFFFDFFW_PPP______BBBBB__TTT;TTWFFFWFFW_P_PPPP_________TTTT;TTWWWWWWWW_PPP__PPP_______TTTT;TTTT________P__T_________TTTTT;TTTWWWWWWWW_P____________TTTTT;TTTWFFDFFFWPPP____________TTTT;TTTWFFWFFFDP_PPP_WWWW_____TTTT;TTTWWWWFFFW____PPDFFWT___TTTTT;TTT___WWWWW____WWWFFW___TTTTTT;TTTT___TT______WFFFFW_TTTTTTTT;TTTTT______TT__WFFFFWTTTTTTTTT;TTTTTTT__TTTTT_WWWWWWTTTTTTTTT;TTTTTTTTTTTTTTT__TTTTTTTTTTTTT;TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT;TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT;";
	public static String mapMercenaryShooting = "TTTTTTTTTTTTTTTTTTTTTT;TTTTTTTTTTTTTTTTTTTTTT;TTTTTTTTTT___TTTTTTTTT;TTTTTTTT___T___TTTTTTT;TTTTTTTT________TTTTTT;TTTTTTTT_P__WWWWWWTTTT;TTTTTT___P__WFFFFWTTTT;TTT____TPP__WFFFFWTTTT;TT___PP_P___WFFWWWTTTT;TTBBB_PPPP__WWDWT___TT;TT___PP__P____PP___PPP;TTT____T_PPP___PPPPP_T;TTTTT______PPPPP__TTTT;TTTTTTTTTT____TTTTTTTT;TTTTTTTTTTTTTTTTTTTTTT;TTTTTTTTTTTTTTTTTTTTTT;";
	public static String mapMercenaryPlains = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT;TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT;TTTTTT__TTTTTT___TTTTTTTTTT__TTT;TTTT____TTTT_______TTTT_TT____TT;TTTTT__TTT____________________TT;TTTTTT_TT________________TTT_TTT;TTWTWW_TT_______________TTTTTTTT;TTWFFFFW______TT___TT___TT_TTTTT;TT_FFFF_______TT__TTT______TTTTT;TTWFFFWW______TTTTTT_____P_TTTTT;TT_FFWTT__T____TTTT________PPPPT;TTTW_TT__TTTT__T_TTT__TT__P_TTPP;TTTTTTT__TTT______TTTTTT___TTTTT;TTT_TTT___TTT____TTTTTTT___TTTTT;TT___T_____TTT___TTTTTT_____TTTT;TTT________TTTT____TT________TTT;TTT_________TTT_________TTT__TTT;TTT__________T__________TTTT__TT;TT__P__TTT______T______TTTTT__TT;PPP___TTTTT____TT__TT_TTT_TT_TTT;TT_P__TTTTTT______TTTTTT_____TTT;TTT____TTTTTT_____TTTTTT_____TTT;TTTT___TTTTTT_______TTTTT___TTTT;TTTT__TTT__T__________TT____TTTT;TTT____T___________________TTTTT;TTT_______T______TT_____T__TTTTT;TTT_T____T____P__TTT___TTT__TTTT;TT_______T____P_P_TTT__TT____TTT;TT___TT____TT_PP__TTT_TTT___TTTT;TTT_TTTT__TTTTTP_TTTTTTTTT_TTTTT;TTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTT;TTTTTTTTTTTTTTPTTTTTTTTTTTTTTTTT;";
	//Map name ideas: Vamas
}